before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
bundler_args: --without development production --quiet
env:
  - GEM=api DB=mysql
before_install:
  - gem update --system 2.6.1
  - gem --version
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
script:
  - bundle exec rake test_app
  - bundle exec rake spec
rvm:
  - 2.1
