sudo: required
dist: trusty

language: ruby

cache:
  bundler: true

env:
  - GEM=api DB=mysql
  - GEM=api DB=postgres
  - GEM=backend DB=mysql
  - GEM=backend DB=postgres
  - GEM=core DB=mysql
  - GEM=core DB=postgres
  - GEM=frontend DB=mysql
  - GEM=frontend DB=postgres
  - GEM=sample DB=mysql
  - GEM=sample DB=postgres

before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"

  - mkdir travis-phantomjs
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version

script:
  - bundle exec rake test_app
  - bundle exec rake spec

rvm:
  - 2.3.1
  - 2.2.5

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
